services:
  node-1:
    image: raftkv-v23:latest
    restart: always
    cap_add: [NET_ADMIN]
    mem_limit: 512m
    cpus: 0.5
    environment:
      NODE_ID: node-1
      GRPC_PORT: "9700"
      HTTP_PORT: "9000"
      PEERS: node-2=node-2:9701,node-3=node-3:9702
    ports: ["9700:9700", "9710:9000"]
    networks: [v23-net]

  node-2:
    image: raftkv-v23:latest
    restart: always
    cap_add: [NET_ADMIN]
    mem_limit: 512m
    cpus: 0.5
    environment:
      NODE_ID: node-2
      GRPC_PORT: "9701"
      HTTP_PORT: "9000"
      PEERS: node-1=node-1:9700,node-3=node-3:9702
    ports: ["9701:9701", "9711:9000"]
    networks: [v23-net]

  node-3:
    image: raftkv-v23:latest
    restart: always
    cap_add: [NET_ADMIN]
    mem_limit: 512m
    cpus: 0.5
    environment:
      NODE_ID: node-3
      GRPC_PORT: "9702"
      HTTP_PORT: "9000"
      PEERS: node-1=node-1:9700,node-2=node-2:9701
    ports: ["9702:9702", "9712:9000"]
    networks: [v23-net]

  node-4:
    image: raftkv-v23:latest
    restart: always
    cap_add: [NET_ADMIN]
    mem_limit: 512m
    cpus: 0.5
    environment:
      NODE_ID: node-4
      GRPC_PORT: "9703"
      HTTP_PORT: "9000"
      PEERS: ""
    ports: ["9703:9703", "9713:9000"]
    networks: [v23-net]

networks:
  v23-net:
    driver: bridge